<a href="https://colab.research.google.com/github/YadiBelly/demo-ml-github/blob/main/labs/myNumpyIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
miles = 1820 
gallons = 97 
mpg = miles / gallons 
print(mpg)

18.762886597938145


In [54]:
print(mpg)

18.762886597938145


# Intro to Numpy 
## importing a libary into python 


In [25]:
import numpy as np 
bodhi = np.array({1, 2, 3, 4})

In [26]:
bodhi

array({1, 2, 3, 4}, dtype=object)

In [27]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

In [28]:
arr2d 

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
import numpy 
arr3 = numpy.array([1, 2, 3])

In [30]:
import numpy as deeplearninglibarary 
arr4 = deeplearninglibarary.array([1, 2, 3])

## other ways of ceating an array 
### first a python example



In [2]:
pArr = [x for x in range(10)]

In [3]:
pArr

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
Parr2d = [[x + y * 10 for x in range(10)] for y in range(10)]
Parr2d

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
 [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
 [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
 [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
 [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
 [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
 [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
 [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]

#### In Numpy

In [31]:
## no need to import numpy 
nArr = np.arange(100)

In [32]:
nArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [40]:
nArr2 = nArr.reshape((10,10))

In [41]:
nArr[3]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [42]:
nArr2[1][3]

13

In [44]:
nArr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

## all the same stuff as Python- Why Bother?
#speed

In [46]:
%time pyT1 = [[x + y * 1000 for x in range(1000)] for y in range (1000)]

CPU times: user 126 ms, sys: 13.9 ms, total: 140 ms
Wall time: 142 ms


In [47]:
%time nuT1 = np.arange(1000000).reshape((1000,1000))

CPU times: user 2.17 ms, sys: 7.19 ms, total: 9.37 ms
Wall time: 8.73 ms


### add 1 to each element 

#### first pythin

In [48]:
def add1 ():
  for i in range(1000):
    for j in range(1000):
      pyT1[i][j] = pyT1[i][j] + 1
%time add1()

CPU times: user 223 ms, sys: 123 µs, total: 223 ms
Wall time: 244 ms


In [49]:
%time nuT1 + 1

CPU times: user 915 µs, sys: 6.18 ms, total: 7.09 ms
Wall time: 9.19 ms


array([[      1,       2,       3, ...,     998,     999,    1000],
       [   1001,    1002,    1003, ...,    1998,    1999,    2000],
       [   2001,    2002,    2003, ...,    2998,    2999,    3000],
       ...,
       [ 997001,  997002,  997003, ...,  997998,  997999,  998000],
       [ 998001,  998002,  998003, ...,  998998,  998999,  999000],
       [ 999001,  999002,  999003, ...,  999998,  999999, 1000000]])

## Numpy Functions

In [50]:
nuT1.mean()

499999.5

In [51]:
nuT1.sum()

499999500000

In [55]:
mpg

18.762886597938145